version: "3"
services:
  node-spanish-roasters:
    image: "node:current-alpine"
    working_dir: /home/spanish-roasters
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/spanish-roasters

